config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'users#index'

  # get '/users', to: 'users#index'
    resources :users, only: [:index, :new, :create, :show, :edit, :update]
    resources :reservations, only: [:new, :create]
  	get '/about', to: 'users#about'
  	get '/rates', to: 'users#rates'

    resource :sessions, only: [:new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/reservation.rb
class Reservation < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_reservation, only: [:show, :edit, :update, :destroy]

  # GET /reservations
  # GET /reservations.json
  def index
    @reservations = Reservation.all
  end

  # GET /reservations/1
  # GET /reservations/1.json
  def show
  end

  # GET /reservations/new
  def new
    @reservation = Reservation.new
  end

  # GET /reservations/1/edit
  def edit
  end

  # POST /reservations
  # POST /reservations.json
  def create
    @reservation = Reservation.new(reservation_params)

    respond_to do |format|
      if @reservation.save
        ReservationMailer.welcome_email(@reservation.email).deliver_now

        format.html { redirect_to @reservation, notice: 'Reservation was successfully created.' }
        format.json { render :show, status: :created, location: @reservation }
      else
        format.html { render :new }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reservations/1
  # PATCH/PUT /reservations/1.json
  def update
    respond_to do |format|
      if @reservation.update(reservation_params)
        format.html { redirect_to @reservation, notice: 'Reservation was successfully updated.' }
        format.json { render :show, status: :ok, location: @reservation }
      else
        format.html { render :edit }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservations/1
  # DELETE /reservations/1.json
  def destroy
    @reservation.destroy
    respond_to do |format|
      format.html { redirect_to reservations_url, notice: 'Reservation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reservation
      @reservation = Reservation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reservation_params
      params.require(:reservation).permit(:first_name, :last_name, :email, :phone, :dog_breed, :dog_size, :dog_name, :date_preference)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no"/>
    <title>Pups N Suds Dog Grooming</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- CSS  -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,900" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Comfortaa|Gruppo|Sansita|Unkempt:700" rel="stylesheet">
  </head>

  <body>
    <nav class="white" role="navigation">
      <div class="nav-wrapper container">
        <a id="logo-container" href="#" class="brand-logo">Pups 'n Suds<br /><span>Dog Grooming</span></a>
        <ul class="right hide-on-med-and-down">
          <li><a href="/users">Home</a></li>
          <li><a href="/about">About</a></li>
          <li><a href="/rates">Rates</a></li>
          <li><a href="/reservations/new">Book an Appointment</a></li>
        </ul>

        <ul id="nav-mobile" class="side-nav">
          <li><a href="/users">Home</a></li>
          <li><a href="/about">About</a></li>
          <li><a href="/rates">Rates</a></li>
          <li><a href="/reservations/new">Book an Appointment</a></li>
        </ul>
        <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons cyan-text">menu</i></a>
      </div>
    </nav>


    <%= yield %>

    <footer class="page-footer cyan">
      <div class="container">
        <div class="row">
          <div class="col l6 s12">
            <h5 class="white-text">About Us</h5>
            <p class="grey-text text-lighten-4">
              Pups N Suds is conveniently located in the heart of Burlington.
              <br><br>
              1572 Kerns Rd., Unit 6
              <br>
              Burlington, ON, L7P 3A7
              <br><br>
              Please Call 905-320-9050 to schedule an appointment today!
              <!-- We are a team of college students working on this project like it's our full time job. Any amount would help support and continue development on this project and is greatly appreciated. -->
            </p>
          </div>
          <div class="col l3 s12">
            <h5 class="white-text">Hours of operation</h5>
            <ul>
              <li class="white-text">Mon - Fri: 9:00am - 8:00pm</li>
              <li class="white-text">Weekends: 9:00am - 3:00pm</li>
              <li class="white-text">Closed Holidays</li>

              <!-- <li><a class="white-text" href="#!">Link 1</a></li>
              <li><a class="white-text" href="#!">Link 2</a></li>
              <li><a class="white-text" href="#!">Link 3</a></li>
              <li><a class="white-text" href="#!">Link 4</a></li> -->
            </ul>
          </div>
          <div class="col l3 s12">
            <!-- <h5 class="white-text">Connect</h5> -->
            <!-- TODO add links to facebook, email, phone ** with icons -->
            <!-- <ul>
              <li><a class="white-text" href="#!">Link 1</a></li>
              <li><a class="white-text" href="#!">Link 2</a></li>
              <li><a class="white-text" href="#!">Link 3</a></li>
              <li><a class="white-text" href="#!">Link 4</a></li>
            </ul> -->
          </div>
        </div>
      </div>
      <div class="footer-copyright">
        <!-- <div class="container">
        Made by <a class="brown-text text-lighten-3" href="http://materializecss.com">Materialize</a>
        </div> -->
      </div>
    </footer>
    <!--  Scripts-->
    <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>

  </body>
</html>

app/views/reservations/_form.html.erb
<%= form_for(reservation) do |f| %>
  <% if reservation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>

      <ul>
      <% reservation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>

  <div class="field">
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :phone %>
    <%= f.text_field :phone %>
  </div>

  <div class="field">
    <%= f.label :dog_breed %>
    <%= f.text_field :dog_breed %>
  </div>

  <div class="field">
    <%= f.label :dog_size %>
    <%= f.text_field :dog_size %>
  </div>

  <div class="field">
    <%= f.label :dog_name %>
    <%= f.text_field :dog_name %>
  </div>

  <div class="field">
    <%= f.label :date_preference %>
    <%= f.text_field :date_preference %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reservations/edit.html.erb
<h1>Editing Reservation</h1>

<%= render 'form', reservation: @reservation %>

<%= link_to 'Show', @reservation %> |
<%= link_to 'Back', reservations_path %>

app/views/reservations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reservations</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Dog breed</th>
      <th>Dog size</th>
      <th>Dog name</th>
      <th>Date preference</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reservations.each do |reservation| %>
      <tr>
        <td><%= reservation.first_name %></td>
        <td><%= reservation.last_name %></td>
        <td><%= reservation.email %></td>
        <td><%= reservation.phone %></td>
        <td><%= reservation.dog_breed %></td>
        <td><%= reservation.dog_size %></td>
        <td><%= reservation.dog_name %></td>
        <td><%= reservation.date_preference %></td>
        <td><%= link_to 'Show', reservation %></td>
        <td><%= link_to 'Edit', edit_reservation_path(reservation) %></td>
        <td><%= link_to 'Destroy', reservation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reservation', new_reservation_path %>

app/views/reservations/new.html.erb
<h1>New Reservation</h1>

<%= render 'form', reservation: @reservation %>

<%= link_to 'Back', reservations_path %>

app/views/reservations/reservation.html.erb
HELLOOOO

app/views/reservations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @reservation.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @reservation.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @reservation.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @reservation.phone %>
</p>

<p>
  <strong>Dog breed:</strong>
  <%= @reservation.dog_breed %>
</p>

<p>
  <strong>Dog size:</strong>
  <%= @reservation.dog_size %>
</p>

<p>
  <strong>Dog name:</strong>
  <%= @reservation.dog_name %>
</p>

<p>
  <strong>Date preference:</strong>
  <%= @reservation.date_preference %>
</p>

<%= link_to 'Edit', edit_reservation_path(@reservation) %> |
<%= link_to 'Back', reservations_path %>

app/views/users/about.html.erb
<h2>About us</h2>

Pups N Suds is conveniently located in the heart of Burlington.

1572 Kerns Rd., Unit 6
Burlington, ON L7P 3A7

Our hours of operation are as follows:
Monday - Friday: 9:00am - 8:00pm
Weekends: 9:00am - 3:00pm
Closed Holidays

Please Call 905-320-9050 to schedule an appointment today!

image of salon

map

app/views/users/edit.html.erb
EDIT

app/views/users/index.html.erb
<div id="index-banner" class="parallax-container">
  <div class="section no-pad-bot">
    <div class="container">
      <br><br>
      <h1 class="header center cyan-text par_h1">Welcome to Pups N Suds professional dog grooming.</h1>
      <br><br>
      <div class="row center">
        <h5 class="header col s12 light par_h5">Burlington's Friendliest Dog Groomer</h5>
      </div>
      <!-- <div class="row center">
        <a href="http://materializecss.com/getting-started.html" id="download-button" class="btn-large waves-effect waves-light teal lighten-1">Get Started</a>
      </div> -->
      <br><br>

    </div>
  </div>
  <div class="parallax"><img src="assets/dogs.jpeg" alt="Unsplashed background img 1"></div>
</div>


<div class="container info_container">
  <div class="section info_section">

    <!--   Icon Section   -->
    <div class="row mission">
      <div class="col s12 m5 forty">
        <div class="icon-block forty-div">
          <h2 class="center brown-text paw"><%= image_tag "noun_547449_cc.svg" %></h2>
          <h5 class="center">Mission</h5>

          <p class="light">
          	At Pups N Suds we believe that all dogs deserve to look and feel their best. Pups N Suds prides itself in pampering dogs and making them feel loved.
          	A coat free of mats, burs, tangles and skin free of fleas and ticks means your dog will be comfortable and happy.
          	Regular grooming keeps your pets coat smelling fresh and looking at its best.
          </p>
          <!-- <p class="light">We did most of the heavy lifting for you to provide a default stylings that incorporate our custom components. Additionally, we refined animations and transitions to provide a smoother experience for developers.</p> -->
        </div>
      </div>

      <div class="col s12 m7 sixty">
        <div class="icon-block">
          <h2 class="center brown-text paw"><%= image_tag "dog_house.svg" %></h2>
          <h5 class="center">Your dog's day at the spa includes</h5>

          	<ul class="spa_list">
          		<li class="light">Complete skin analysis</li>
          		<li class="light">Brush out and or clipping</li>
          		<li class="light">Cleaning of the ears</li>
          		<li class="light">Trimming of the nails</li>
          		<li class="light">Bathing with  our hypo-allergenic shampoo</li>
          		<li class="light">Velocity dried and re-brushed</li>
          		<li class="light">We also offer specialized treatments such as flea and skunk baths and medicated shampoos for dry itchy coats.</li>
          	</ul>
          <!-- <p class="light">By utilizing elements and principles of Material Design, we were able to create a framework that incorporates components and animations that provide more feedback to users. Additionally, a single underlying responsive system across all platforms allow for a more unified user experience.</p> -->
        </div>
      </div>

      <!-- <div class="col s12 m4">
        <div class="icon-block">
          <h2 class="center brown-text"><i class="material-icons">settings</i></h2>
          <h5 class="center">Easy to work with</h5>

          <p class="light">We have provided detailed documentation as well as specific code examples to help new users get started. We are also always open to feedback and can answer any questions a user may have about Materialize.</p>
        </div>
      </div> -->
    </div>

  </div>
</div>


<div class="parallax-container valign-wrapper">
  <div class="section no-pad-bot">
    <div class="container">
      <div class="row center">
        <h5 class="header col s12 light">Flexible hours offered to accommodate for those who work.</h5>
        <h5 class="header col s12 light">For more information or to schedule an appointment please call (905) 320-9050.</h5>
      </div>
    </div>
  </div>
  <div class="parallax"><img src="assets/background4.jpg" alt="Unsplashed background img 2"></div>
</div>

<div class="container">
  <div class="section">

    <div class="row">
      <div class="col s12 center">
        <h3><i class="mdi-content-send brown-text"></i></h3>
        <h4>Top Ten reasons why it costs more to get your pet groomed than your own hair cut</h4>
        <!-- <p class="left-align light">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam scelerisque id nunc nec volutpat. Etiam pellentesque tristique arcu, non consequat magna fermentum ac. Cras ut ultricies eros. Maecenas eros justo, ullamcorper a sapien id, viverra ultrices eros. Morbi sem neque, posuere et pretium eget, bibendum sollicitudin lacus. Aliquam eleifend sollicitudin diam, eu mattis nisl maximus sed. Nulla imperdiet semper molestie. Morbi massa odio, condimentum sed ipsum ac, gravida ultrices erat. Nullam eget dignissim mauris, non tristique erat. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;</p> -->
        <ol class="left-align light">
          <li class="light">The likelihood of you pooping on the hairdresser is pretty slim</li>
          <li class="light">You don't bite or scratch your hairdresser</li>
          <li class="light">Your hairdresser only washes and cuts the hair on your head</li>
          <li class="light">Your haircut doesn’t include a manicure and pedicure</li>
          <li class="light">You sit still for your hairdresser</li>
          <li class="light">Your hairdresser doesn't have to remove the boogies from your eyes</li>
          <li class="light">Your hairdresser doesn't have to clean your ears</li>
          <li class="light">Your hairdresser doesn't have to give you a sanitary trim</li>
          <li class="light">You don't go for eight weeks without washing or brushing your hair</li>
          <li class="light">Your hairdresser doesn't wash and clean your rear end</li>
        </ol>
      </div>
    </div>
  </div>
</div>


<div class="parallax-container valign-wrapper">
  <!-- <div class="section no-pad-bot">
    <div class="container">
      <div class="row center">
        <h5 class="header col s12 light">A modern responsive front-end framework based on Material Design</h5>
      </div>
    </div>
  </div> -->
  <!-- <div class="parallax"><img src="assets/background3.jpg" alt="Unsplashed background img 3"></div> -->
  <div class="map">
    <iframe width="100%" height="450" frameborder="0" scrolling="no" style="border:0" src="https://www.google.com/maps/embed/v1/place?q=place_id:ChIJhzjcAgdiK4gRfDBkkKgDXY0&key=AIzaSyADMBa-G766lyfghofGBFAi9Zs-Kf_QvM0" allowfullscreen></iframe>
  </div>
</div>

app/views/users/new.html.erb
NEW

app/views/users/rates.html.erb
<h2>Grooming Rates</h2>

<h3>Prices based on pets in good condition, disposition and breed sizes.</h3>
<section>
	<ul>
		Small (shih tzu, Yorkshire terrier etc.):  $45-$60
		Medium (Cocker Spaniel, Cockapoo etc.)  $50 and up
		Large (Goldens, Airedales etc.):  $60 and up
		X-Large (Berness Mountain Dog etc.):  $80 and up
		Medicated shampoos:  $5.00
		Nail Trimming only:  $10.00
		Paw trimming &amp; nails only:  $15.00
		Flea baths:  $6.00
		Skunk baths:  $10.00
	</ul>
</section>
<p>
	Additional costs may apply if extra time is spent due to the temperament of the dog or heavily matted dogs.
</p>
<p>
	Every step will be taken to ensure your dog is not subjected to any undue pain and discomfort while de-matting.
</p>
<p>
	If the coat is heavily matted it may be in the best interest of the dog to remove the coat.
</p>

<section>
	Full Groom includes:
	<ul>
		De-matting and Pre-groom
		Ear cleaning
		Nail trimming
		Bathing in hypo-allergenic natural shampoos and conditioners
		Complete blow dry
		Professional Scissor shaping
		Please allow 2 - 3 hours for the full grooming process.
		Be sure that your dog's best interest, comfort and happiness are our #1 priority.
		For more information, you can also email us at jsmith@pupsnsuds.ca
	</ul>
</section>

app/views/users/show.html.erb
SHOW